networks:
  web:
    external: true
  voice-db:
    internal: true # no external connectivity at all

services:
  postgres:
    image: postgres:16-alpine
    container_name: voice-postgres
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voice-db
    restart: unless-stopped

  voice-server:
    depends_on:
      - postgres
    build:
      context: .. # build from voice/ root
      dockerfile: server/Dockerfile # but use server/Dockerfile
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - web
      - voice-db
    container_name: voice-server

  coturn:
    build: ../coturn
    env_file:
      - .env.production
    restart: unless-stopped
    network_mode: host
    container_name: voice-coturn

volumes:
  postgres_data:
